#{{ include "testmicroservices.templates.baseService" . }}
{{- define "testmicroservices.templates.baseService" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_e.name }}
spec:
  type: {{ .Values.type | default .Values.global.serviceType }}
  ports:
  {{- range .Values.app_e.ports }}
  - name: "{{ .port }}"
    port: {{ .port }}
    {{- if .protocol}}
    protocol: {{ .protocol }}
    {{- end}}
    targetPort: {{ .targetPort }}
  {{- end}}
  selector:
    service: {{ .Values.app_e.name }}

{{- end }}
