name: app-c

ports:
  - port: 8000
    targetPort: 8000

container:
  image: fastapi-jaeger-app
  name: app-c
  ports:
    - containerPort: 8000
  env:
    - name: OTEL_SERVICE_NAME
      value: app-c
    - name: OTLP_GRPC_ENDPOINT
      value: otel-collector-opentelemetry-collector:4317
    - name: TARGET_ONE_HOST
      value: app-f:8000/cpu_task
    - name: TARGET_TWO_HOST
      value: app-g:8000/io_task
    - name: TARGET_THREE_HOST
      value: ""

configMaps:
  - name: jaeger-config.yml
    mountPath: /testmicroservices/config/jaeger-config.yml
    value: jaeger-config

