global:
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: ""
  defaultImageVersion: latest
  jaeger:
    localAgentHostPort: jaeger:6831
    queueSize: 1000000
    bufferFlushInterval: 10
    samplerType: probabilistic
    samplerParam: 0.01
    disabled: false
    logSpans: false
app-a:
  environment:
    OTEL_SERVICE_NAME: app-a
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: app-b:8000/chain
    TARGET_TWO_HOST: app-c:8000/chain
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-b:
  environment:
    OTEL_SERVICE_NAME: app-b
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: app-d:8000/chain
    TARGET_TWO_HOST: app-e:8000/chain
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-c:
  environment:
    OTEL_SERVICE_NAME: app-c
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: app-f:8000/cpu_task
    TARGET_TWO_HOST: app-g:8000/io_task
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-d:
  environment:
    OTEL_SERVICE_NAME: app-d
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: app-h:8000/io_task
    TARGET_TWO_HOST: app-i:8000/cpu_task
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-e:
  environment:
    OTEL_SERVICE_NAME: app-e
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: app-j:8000/io_task
    TARGET_TWO_HOST: ""
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-f:
  environment:
    OTEL_SERVICE_NAME: app-f
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: ""
    TARGET_TWO_HOST: ""
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-g:
  environment:
    OTEL_SERVICE_NAME: app-g
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: ""
    TARGET_TWO_HOST: ""
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-h:
  environment:
    OTEL_SERVICE_NAME: app-h
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: ""
    TARGET_TWO_HOST: ""
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-i:
  environment:
    OTEL_SERVICE_NAME: app-i
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: ""
    TARGET_TWO_HOST: ""
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
app-j:
  environment:
    OTEL_SERVICE_NAME: app-j
    OTLP_GRPC_ENDPOINT: otel-collector-opentelemetry-collector:4317
    TARGET_ONE_HOST: ""
    TARGET_TWO_HOST: ""
    TARGET_THREE_HOST: ""
  repository:
    image: fastapi-jaeger-app
    tag: latest
