name: app-a

ports:
  - port: 8000
    targetPort: 8000

container:
  image: fastapi-jaeger-app
  name: app-a
  ports:
    - containerPort: 8000
  env:
    - name: OTEL_SERVICE_NAME
      value: app-a
    - name: OTLP_GRPC_ENDPOINT
      value: otel-collector-opentelemetry-collector:4317
    - name: TARGET_ONE_HOST
      value: app-b:8000/chain
    - name: TARGET_TWO_HOST
      value: app-c:8000/chain
    - name: TARGET_THREE_HOST
      value: ""

configMaps:
  - name: jaeger-config.yml
    mountPath: /testmicroservices/config/jaeger-config.yml
    value: jaeger-config
